import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    padding: 20,
    paddingTop: 40,
    transitionProperty: 'background-color',
    transitionDuration: '0.3s',
  },
  darkContainer: {
    backgroundColor: '#2E2E2E',
  },
  lightContainer: {
    backgroundColor: '#F4F4F4',
  },
  title: {
    fontSize: 34,
    textAlign: 'center',
    marginBottom: 20,
    fontWeight: 'bold',
    letterSpacing: 1.2,
    transitionProperty: 'color',
    transitionDuration: '0.3s',
  },
  darkText: {
    color: '#EAEAEA',
  },
  lightText: {
    color: '#333333',
  },
  icon: {
    alignSelf: 'flex-end',
    marginBottom: 10,
    padding: 12,
    borderRadius: 20,
    backgroundColor: '#8BC34A',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
    transitionProperty: 'background-color',
    transitionDuration: '0.3s',
  },
  inputContainer: {
    borderRadius: 15,
    overflow: 'hidden',
    marginBottom: 20,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
    transitionProperty: 'background-color',
    transitionDuration: '0.3s',
  },
  darkInputContainer: {
    backgroundColor: '#444',
  },
  lightInputContainer: {
    backgroundColor: '#F9F9F9',
  },
  input: {
    height: 50,
    borderColor: 'gray',
    borderWidth: 1,
    marginBottom: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    fontSize: 16,
    backgroundColor: '#FFF',
    transitionProperty: 'background-color',
    transitionDuration: '0.3s',
  },
  darkInput: {
    backgroundColor: '#666',
    borderColor: '#888',
  },
  lightInput: {
    backgroundColor: '#FFF',
    borderColor: '#CCC',
  },
  picker: {
    height: 50,
    width: '100%',
    borderRadius: 10,
    marginBottom: 15,
  },
  darkPicker: {
    backgroundColor: '#555',
  },
  lightPicker: {
    backgroundColor: '#FFF',
  },
  result: {
    marginTop: 20,
    fontSize: 24,
    textAlign: 'center',
    fontWeight: 'bold',
    transitionProperty: 'color',
    transitionDuration: '0.3s',
    borderRadius: 10,
    padding: 15,
    backgroundColor: '#88C999',
  },
  clearButton: {
    marginTop: 10,
    padding: 12,
    backgroundColor: '#FF9800',
    borderRadius: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
    transitionProperty: 'background-color',
    transitionDuration: '0.3s',
  },
  clearButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
});